<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'L4 — consumption_entry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE consumption_entry (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                food_id INT NOT NULL,
                quantity_grams NUMERIC(8, 2) NOT NULL,
                consumed_on DATE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_consumption_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
                CONSTRAINT fk_consumption_food FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE RESTRICT
            )
        SQL);
        $this->addSql('CREATE INDEX idx_consumption_user_date ON consumption_entry (user_id, consumed_on)');
        $this->addSql('COMMENT ON COLUMN consumption_entry.consumed_on IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN consumption_entry.created_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE consumption_entry');
    }
}
