<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'L3 — food, food_nutrient, rda + french_unaccent search';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS unaccent');
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'french_unaccent') THEN
                    CREATE TEXT SEARCH CONFIGURATION french_unaccent (COPY = french);
                    ALTER TEXT SEARCH CONFIGURATION french_unaccent
                        ALTER MAPPING FOR hword, hword_part, word
                        WITH unaccent, french_stem;
                END IF;
            END$$;
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE food (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                alim_code VARCHAR(16) NOT NULL,
                name_fr VARCHAR(255) NOT NULL,
                group_name VARCHAR(255) DEFAULT NULL,
                sub_group_name VARCHAR(255) DEFAULT NULL,
                search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('french_unaccent', name_fr)) STORED,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_food_alim_code ON food (alim_code)');
        $this->addSql('CREATE INDEX idx_food_search_vector ON food USING GIN (search_vector)');

        $this->addSql(<<<'SQL'
            CREATE TABLE food_nutrient (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                food_id INT NOT NULL,
                nutrient_code VARCHAR(16) NOT NULL,
                amount_per_100g NUMERIC(12, 4) NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_food_nutrient_food FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_food_nutrient ON food_nutrient (food_id, nutrient_code)');
        $this->addSql('CREATE INDEX idx_food_nutrient_code ON food_nutrient (nutrient_code)');

        $this->addSql(<<<'SQL'
            CREATE TABLE rda (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                nutrient_code VARCHAR(16) NOT NULL,
                sex VARCHAR(10) DEFAULT NULL,
                age_min INT NOT NULL,
                age_max INT NOT NULL,
                amount NUMERIC(12, 4) NOT NULL,
                source VARCHAR(32) DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_rda_lookup ON rda (nutrient_code, sex, age_min, age_max)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE rda');
        $this->addSql('DROP TABLE food_nutrient');
        $this->addSql('DROP TABLE food');
        $this->addSql('DROP TEXT SEARCH CONFIGURATION IF EXISTS french_unaccent');
    }
}
