<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'L5 — recipe_suggestion';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_suggestion (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                target_nutrients JSON NOT NULL,
                response_markdown TEXT DEFAULT NULL,
                status VARCHAR(16) NOT NULL,
                duration_ms INT DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_recipe_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
            )
        SQL);
        $this->addSql('CREATE INDEX idx_recipe_user_date ON recipe_suggestion (user_id, requested_at)');
        $this->addSql('COMMENT ON COLUMN recipe_suggestion.requested_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE recipe_suggestion');
    }
}
